vich_uploader:
    db_driver: orm
    mappings:
        livres_files:                  # <-- ici, le nom doit correspondre à l'entité
            uri_prefix: /uploads/files
            upload_destination: '%kernel.project_dir%/public/uploads/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
